# $Id: GNUmakefile,v 1.20 2004/03/03 16:08:24 jimb Exp $
# Author:	Jim E. Brooks  http://www.jimbrooks.org
# Desc:		Makefile for building a static library from C++ source files.
# Notes:
# =============================================================================

SRC_DIR			:= src
OUT_DIR			:= out
GFX_DIR			:= .
TARGET_NAME		:= "gfx library"
TARGET_LIB		:= $(OUT_DIR)/gfx.a
C_SRCS			:= gfx_iter.cc \
                   gfx_math.cc \
                   gfx_opengl.cc \
                   gfx_misc.cc \
                   gfx_os.cc \
                   gfx_random.cc
# GFX_H_SRCS already defined in GNUmakefile_common.
include $(GFX_DIR)/GNUmakefile_common
