# $Id: GNUmakefile,v 1.7 2004/02/09 16:17:04 jimb Exp $
# Author:	Jim E. Brooks  http://www.jimbrooks.org
# Desc:		Makefile to build an OpenGL program.
# =============================================================================

SRC_DIR			:= src
OUT_DIR			:= out
GFX_DIR			:= ../gfx
TARGET_NAME		:= "Boing"
TARGET_EXEC		:= $(OUT_DIR)/boing
C_SRCS			:= boing.cc
H_SRCS			:= boing.h
include $(GFX_DIR)/GNUmakefile_common
